
bin_center_x: 1
bin_center_y: 0
bin_center_z: 0.7

bin_size_x: 0.25
bin_size_y: 0.75
bin_size_z: 0.25

roll_default: 0
pitch_default: 3.14
yaw_default: 0

roll_range: 0.707
pitch_range: 0.707
yaw_range: 0.707

approach_distance: 0.1
deapproach_height: 0.20
